name:                blogger1
version:             0.1.0.0
github:              "githubuser/blogger"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/blogger#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 2.0.1
- aeson

library:
  source-dirs: src
  dependencies:
    - markdown
    - blaze-html
    - text
    - directory
    - transformers
    - mtl
    - extra
    - uri-encode
    - aeson
    - lens
    - unordered-containers
    - serverless-haskell

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -static
    - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - blogger1

tests:
  blogger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blogger1
    - text
    - hspec
    - hspec-discover
    - blaze-html

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric