service: blogger1

provider:
  name: aws
  region: ap-southeast-2
  state: prod

package:
  individually: true
  
functions:
  haskell:
    handler: src/Lib.handler
    runtime: provided
    package:
      artifact: build/function.zip
    layers:
      - arn:aws:lambda:ap-southeast-2:785355572843:layer:aws-haskell-runtime:2
    events:
      - http:
          path: /test/{name}
          method: get