flags: {}
packages:
- .
extra-deps:
- QuickCheck-2.11.3
- aeson-1.3.0.0
- amazonka-core-1.5.0
- amazonka-kinesis-1.5.0
- amazonka-s3-1.5.0
- conduit-1.2.13.1
- conduit-extra-1.2.3.2
- exceptions-0.10.0
- resourcet-1.1.11
- serverless-haskell-0.4.2
- xml-conduit-1.4.0.4
resolver: lts-11.3
