name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'
        key: ${{ runner.os }}-hacks-blogger-cabal-store
    - run: |
        mkdir -p build/src
        stack clean
        stack build
        cp $(stack path --local-install-root)/bin/bootstrap build
        cp -rf ./src/raw ./build/src
        cd build && zip -r function.zip ./ && rm -rf src && rm bootstrap && cd ..
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          /home/runner/.stack
          /var/lib/docker/
  
    - name: artifact
      uses: actions/upload-artifact@v2
      with:
        name: function.zip
        path: ./build
