name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'
    - run: |
        mkdir -p build/src
        stack clean --docker
        stack build --docker
        cp $(stack --docker path --local-install-root)/bin/bootstrap build
        cp -rf ./src/raw ./build/src
        cd build && zip -r function.zip ./ && rm -rf src && rm bootstrap && cd ..
